### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Milanzor** [Milanzor/builly#1]
- [x] Research wether a frontend framework is a good way to go (React/Vue/etc)
- [ ] Rebuild frontend with VueJS
- [ ] Add new and edit existing builders through the interface
- [x] Show builder log activity in favicon
- [x] Collapse builder details
- [ ] Make the log terminal bigger
- [x] Split code a bit and comment more
- [x] Limit commands to `yarn` and `npm`
